import React, { useMemo, useState } from "react";
import {
  Archive,
  CheckCircle2,
  Clock3,
  Download,
  Eye,
  FileCode2,
  FileSpreadsheet,
  FileText,
  Filter,
  FolderOpen,
  MoreVertical,
  RefreshCw,
  Search,
  ShieldCheck,
  Trash2,
  X,
} from "lucide-react";
import "./GeneratedFiles.css";

const initialFiles = [
  {
    id: 1,
    name: "Inspection_Approval_Note.docx",
    type: "Document",
    extension: "DOCX",
    size: "1.2 MB",
    created: "Today, 09:42 AM",
    agent: "Document Writer Agent",
    task: "Inspection report approval",
    status: "Completed",
  },
  {
    id: 2,
    name: "Safety_Analysis_Report.pdf",
    type: "PDF",
    extension: "PDF",
    size: "2.4 MB",
    created: "Today, 09:18 AM",
    agent: "Analysis Agent",
    task: "Safety inspection analysis",
    status: "Completed",
  },
  {
    id: 3,
    name: "Equipment_Maintenance.xlsx",
    type: "Spreadsheet",
    extension: "XLSX",
    size: "684 KB",
    created: "Yesterday, 04:36 PM",
    agent: "Data Analysis Agent",
    task: "Maintenance data analysis",
    status: "Completed",
  },
  {
    id: 4,
    name: "SOP_Compliance_Check.docx",
    type: "Document",
    extension: "DOCX",
    size: "934 KB",
    created: "Yesterday, 02:11 PM",
    agent: "ASTRA Agent",
    task: "SOP compliance verification",
    status: "Completed",
  },
  {
    id: 5,
    name: "Inspection_Findings.csv",
    type: "Spreadsheet",
    extension: "CSV",
    size: "118 KB",
    created: "Sep 3, 2026, 11:24 AM",
    agent: "Data Analysis Agent",
    task: "Extract structured findings",
    status: "Completed",
  },
  {
    id: 6,
    name: "local_rag_retriever.py",
    type: "Code",
    extension: "PY",
    size: "16 KB",
    created: "Sep 3, 2026, 10:03 AM",
    agent: "Coding Agent",
    task: "Create RAG retriever",
    status: "Completed",
  },
];

const typeIcons = {
  Document: FileText,
  PDF: FileText,
  Spreadsheet: FileSpreadsheet,
  Code: FileCode2,
};

function GeneratedFiles() {
  const [files, setFiles] = useState(initialFiles);
  const [query, setQuery] = useState("");
  const [filter, setFilter] = useState("All Types");
  const [selectedFile, setSelectedFile] = useState(null);
  const [message, setMessage] = useState("");

  const filteredFiles = useMemo(() => {
    return files.filter((file) => {
      const matchesQuery =
        file.name.toLowerCase().includes(query.toLowerCase()) ||
        file.task.toLowerCase().includes(query.toLowerCase()) ||
        file.agent.toLowerCase().includes(query.toLowerCase());

      const matchesFilter =
        filter === "All Types" || file.type === filter;

      return matchesQuery && matchesFilter;
    });
  }, [files, query, filter]);

  const showMessage = (text) => {
    setMessage(text);
    setTimeout(() => setMessage(""), 2200);
  };

  const handleDownload = (file) => {
    const content = `ASTRA Generated File\n\nFile: ${file.name}\nAgent: ${file.agent}\nTask: ${file.task}\nStatus: ${file.status}\n\nThis is a frontend demo placeholder. Connect the download action to your FastAPI generated-file endpoint.`;
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement("a");
    anchor.href = url;
    anchor.download = `${file.name}.demo.txt`;
    anchor.click();
    URL.revokeObjectURL(url);
    showMessage(`Download started for ${file.name}`);
  };

  const handleDelete = (id) => {
    setFiles((items) => items.filter((file) => file.id !== id));
    setSelectedFile(null);
    showMessage("File removed from the generated-files list.");
  };

  const handleRefresh = () => {
    setFiles(initialFiles);
    setQuery("");
    setFilter("All Types");
    showMessage("Generated files refreshed.");
  };

  return (
    <div className="generated-page">
      {message && <div className="gf-toast">{message}</div>}

      <section className="gf-hero">
        <div>
          <span className="gf-eyebrow">LOCAL DELIVERABLE MANAGEMENT</span>
          <h1>Generated Files</h1>
          <p>
            View and manage documents, spreadsheets, reports, and code
            generated by ASTRA agents during local task execution.
          </p>
        </div>

        <div className="gf-local-badge">
          <ShieldCheck size={17} />
          <span>Generated Locally</span>
          <span className="gf-live-dot" />
        </div>
      </section>

      <section className="gf-stat-grid">
        <div className="gf-stat-card">
          <div className="gf-stat-icon"><Archive size={19} /></div>
          <div>
            <span>Total Files</span>
            <strong>{files.length + 12}</strong>
            <small>Across ASTRA tasks</small>
          </div>
        </div>

        <div className="gf-stat-card">
          <div className="gf-stat-icon"><FileText size={19} /></div>
          <div>
            <span>Documents</span>
            <strong>12</strong>
            <small>DOCX & PDF</small>
          </div>
        </div>

        <div className="gf-stat-card">
          <div className="gf-stat-icon"><FileSpreadsheet size={19} /></div>
          <div>
            <span>Spreadsheets</span>
            <strong>4</strong>
            <small>XLSX & CSV</small>
          </div>
        </div>

        <div className="gf-stat-card">
          <div className="gf-stat-icon"><FileCode2 size={19} /></div>
          <div>
            <span>Code Files</span>
            <strong>2</strong>
            <small>Generated by agents</small>
          </div>
        </div>
      </section>

      <section className="gf-toolbar">
        <div className="gf-search">
          <Search size={17} />
          <input
            value={query}
            onChange={(event) => setQuery(event.target.value)}
            placeholder="Search generated files, tasks or agents..."
          />
          {query && (
            <button onClick={() => setQuery("")} aria-label="Clear search">
              <X size={15} />
            </button>
          )}
        </div>

        <div className="gf-actions">
          <div className="gf-filter">
            <Filter size={15} />
            <select
              value={filter}
              onChange={(event) => setFilter(event.target.value)}
            >
              <option>All Types</option>
              <option>Document</option>
              <option>PDF</option>
              <option>Spreadsheet</option>
              <option>Code</option>
            </select>
          </div>

          <button className="gf-refresh" onClick={handleRefresh}>
            <RefreshCw size={15} />
            Refresh
          </button>
        </div>
      </section>

      <div className="gf-main-grid">
        <section className="gf-files-card">
          <div className="gf-card-header">
            <div>
              <span className="gf-eyebrow light">RECENT DELIVERABLES</span>
              <h2>ASTRA Generated Files</h2>
            </div>
            <span className="gf-result-count">
              {filteredFiles.length} shown
            </span>
          </div>

          <div className="gf-file-list">
            {filteredFiles.length === 0 ? (
              <div className="gf-empty">
                <FolderOpen size={30} />
                <strong>No files found</strong>
                <span>Try changing your search or file type filter.</span>
              </div>
            ) : (
              filteredFiles.map((file) => {
                const Icon = typeIcons[file.type] || FileText;

                return (
                  <div className="gf-file-row" key={file.id}>
                    <div className={`gf-file-icon ${file.extension.toLowerCase()}`}>
                      <Icon size={20} />
                    </div>

                    <div className="gf-file-info">
                      <strong>{file.name}</strong>
                      <div>
                        <span>{file.type}</span>
                        <i />
                        <span>{file.size}</span>
                        <i />
                        <span>{file.created}</span>
                      </div>
                      <small>
                        <span>Generated by</span> {file.agent} • {file.task}
                      </small>
                    </div>

                    <div className="gf-complete">
                      <CheckCircle2 size={14} />
                      Completed
                    </div>

                    <div className="gf-row-actions">
                      <button
                        title="View details"
                        onClick={() => setSelectedFile(file)}
                      >
                        <Eye size={16} />
                      </button>
                      <button
                        title="Download"
                        onClick={() => handleDownload(file)}
                      >
                        <Download size={16} />
                      </button>
                      <button
                        title="Delete"
                        onClick={() => handleDelete(file.id)}
                      >
                        <Trash2 size={15} />
                      </button>
                    </div>

                    <button className="gf-more" aria-label="More options">
                      <MoreVertical size={17} />
                    </button>
                  </div>
                );
              })
            )}
          </div>
        </section>

        <aside className="gf-side">
          <div className="gf-pipeline-card">
            <span className="gf-eyebrow light">GENERATION PIPELINE</span>
            <h2>From task to deliverable</h2>

            <div className="gf-pipeline">
              <div className="gf-pipe-step">
                <span>1</span>
                <div>
                  <strong>Agent Task</strong>
                  <small>User request understood</small>
                </div>
              </div>
              <div className="gf-pipe-line" />
              <div className="gf-pipe-step">
                <span>2</span>
                <div>
                  <strong>Reasoning & Tools</strong>
                  <small>RAG, sandbox & local models</small>
                </div>
              </div>
              <div className="gf-pipe-line" />
              <div className="gf-pipe-step">
                <span>3</span>
                <div>
                  <strong>Document Writer</strong>
                  <small>Formats the final output</small>
                </div>
              </div>
              <div className="gf-pipe-line" />
              <div className="gf-pipe-step final">
                <span><CheckCircle2 size={15} /></span>
                <div>
                  <strong>Generated File</strong>
                  <small>Ready for review</small>
                </div>
              </div>
            </div>
          </div>

          <div className="gf-security-card">
            <div className="gf-security-icon">
              <ShieldCheck size={21} />
            </div>
            <div>
              <strong>Sovereign file generation</strong>
              <p>
                Generated deliverables remain inside the configured local
                ASTRA environment.
              </p>
            </div>
          </div>

          <div className="gf-summary-card">
            <div className="gf-summary-header">
              <span>ACTIVITY SUMMARY</span>
              <Clock3 size={15} />
            </div>

            <div className="gf-summary-item">
              <span>Last generated</span>
              <strong>09:42 AM</strong>
            </div>
            <div className="gf-summary-item">
              <span>Files this week</span>
              <strong>18</strong>
            </div>
            <div className="gf-summary-item">
              <span>Failed generations</span>
              <strong>0</strong>
            </div>
          </div>
        </aside>
      </div>

      {selectedFile && (
        <div className="gf-modal-backdrop" onClick={() => setSelectedFile(null)}>
          <div className="gf-modal" onClick={(event) => event.stopPropagation()}>
            <div className="gf-modal-header">
              <div>
                <span className="gf-eyebrow">FILE DETAILS</span>
                <h2>{selectedFile.name}</h2>
              </div>
              <button onClick={() => setSelectedFile(null)}>
                <X size={18} />
              </button>
            </div>

            <div className="gf-modal-body">
              <div><span>File type</span><strong>{selectedFile.extension}</strong></div>
              <div><span>Size</span><strong>{selectedFile.size}</strong></div>
              <div><span>Status</span><strong>{selectedFile.status}</strong></div>
              <div><span>Generated by</span><strong>{selectedFile.agent}</strong></div>
              <div><span>Task</span><strong>{selectedFile.task}</strong></div>
              <div><span>Created</span><strong>{selectedFile.created}</strong></div>
            </div>

            <div className="gf-modal-footer">
              <button className="gf-secondary" onClick={() => setSelectedFile(null)}>
                Close
              </button>
              <button
                className="gf-primary"
                onClick={() => handleDownload(selectedFile)}
              >
                <Download size={15} />
                Download
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

export default GeneratedFiles;
