function GeneratedFiles() {

  return (

    <div className="empty-page">

      <h2>Generated Files</h2>

      <p>
        View Word, Excel, PowerPoint and code files generated by AI.
      </p>

    </div>

  );

}

export default GeneratedFiles;